version: '3.8'

services:
  node-app:
    image: chesnokov70/node-app:${BUILD_ID}
    container_name: node-app
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - node-app
